#!/usr/bin/env python3
"""Global (canonical) training-label vocabulary for the closed-vocab ConSE baselines.

The ConSE baselines (CrossHAR, LiMU-BERT, ssl/harnet) each train ONE closed classifier whose output
vocabulary is the set of every training dataset's activities. We build that vocabulary from the
**canonical** labels (`data.scripts.labels.canonical_labels`), so a synonym never occupies two output
classes (this is the harmonised label vocabulary the ConSE bridge maps into SBERT text space).

Regenerate whenever the training datasets or their `activities` change — the vocabulary defines label
indices, so any cached ConSE head must be re-fit afterwards.

    python -m data.scripts.labels.build_global_label_mapping   # writes data/labels/global_labels.json
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List, Optional

from data.scripts.labels.canonical_labels import canonicalize

REPO = Path(__file__).resolve().parents[3]
TRAIN_DATASETS = [
    "uci_har", "hhar", "pamap2", "wisdm", "kuhar", "unimib_shar", "hapt", "mhealth", "capture24",
]
OUT_PATH = REPO / "data" / "labels" / "global_labels.json"


def global_label_vocabulary(train_datasets: Optional[List[str]] = None) -> List[str]:
    """Sorted list of canonical activity labels across the training datasets (the ConSE vocabulary)."""
    labels = set()
    for ds in train_datasets or TRAIN_DATASETS:
        meta = json.loads((REPO / "data" / "datasets" / ds / "metadata.json").read_text())
        labels.update(canonicalize(a) for a in meta.get("activities", []))
    return sorted(labels)


def main() -> None:
    vocab = global_label_vocabulary()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps({
        "description": ("Canonical training-label vocabulary (ConSE closed-vocab). Sorted union of "
                        f"canonicalized activities across {len(TRAIN_DATASETS)} training datasets. "
                        "Generated by data.scripts.labels.build_global_label_mapping — do not hand-edit."),
        "labels": vocab,
        "num_labels": len(vocab),
    }, indent=2) + "\n")
    print(f"wrote {OUT_PATH} — {len(vocab)} canonical labels")


if __name__ == "__main__":
    main()
